# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the
# command line, check the documentation for more details about this.
# For more details on how to configure your build environment visit
# http://www.gradle.org/configure-gradle-for-your-environment

# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and does not include resources from the
# dependencies, thereby reducing the size of the R class for that library
android.nonTransitiveRClass=true

# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

# Enable Jetpack Compose compiler metrics
compose.metrics.enabled=false
android.useAndroidX=true
android.enableJetifier=true
